// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 9 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int readme_9 = 9;
	/// <summary>PID: 9 | Type: read</summary>
	public const int readme = 9;
	/// <summary>PID: 92 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int sysuptimegroupresultafterretries_92 = 92;
	/// <summary>PID: 92 | Type: read</summary>
	public const int sysuptimegroupresultafterretries = 92;
	/// <summary>PID: 95 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int sysuptimebuffer_95 = 95;
	/// <summary>PID: 95 | Type: read</summary>
	public const int sysuptimebuffer = 95;
	/// <summary>PID: 100 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int sysuptime_100 = 100;
	/// <summary>PID: 100 | Type: read</summary>
	public const int sysuptime = 100;
	/// <summary>PID: 101 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int sysname_101 = 101;
	/// <summary>PID: 101 | Type: read</summary>
	public const int sysname = 101;
	/// <summary>PID: 102 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int syscontact_102 = 102;
	/// <summary>PID: 102 | Type: read</summary>
	public const int syscontact = 102;
	/// <summary>PID: 103 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int syslocation_103 = 103;
	/// <summary>PID: 103 | Type: read</summary>
	public const int syslocation = 103;
	/// <summary>PID: 104 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int sysdescr_104 = 104;
	/// <summary>PID: 104 | Type: read</summary>
	public const int sysdescr = 104;
	/// <summary>PID: 492 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int countergroupafterretries_492 = 492;
	/// <summary>PID: 492 | Type: read</summary>
	public const int countergroupafterretries = 492;
	/// <summary>PID: 494 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int countersnmpagentrestartflag_494 = 494;
	/// <summary>PID: 494 | Type: read</summary>
	public const int countersnmpagentrestartflag = 494;
	/// <summary>PID: 500 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int counter_500 = 500;
	/// <summary>PID: 500 | Type: read</summary>
	public const int counter = 500;
	/// <summary>PID: 501 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int counterrate_501 = 501;
	/// <summary>PID: 501 | Type: read</summary>
	public const int counterrate = 501;
	/// <summary>PID: 502 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int counterratedata_502 = 502;
	/// <summary>PID: 502 | Type: read</summary>
	public const int counterratedata = 502;
	/// <summary>PID: 992 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int streamsgroupafterretries_992 = 992;
	/// <summary>PID: 992 | Type: read</summary>
	public const int streamsgroupafterretries = 992;
	/// <summary>PID: 994 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int streamssnmpagentrestartflag_994 = 994;
	/// <summary>PID: 994 | Type: read</summary>
	public const int streamssnmpagentrestartflag = 994;
	/// <summary>PID: 995 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int streamsratecalculationsmethod_995 = 995;
	/// <summary>PID: 995 | Type: read</summary>
	public const int streamsratecalculationsmethod = 995;
	public class Write
	{
		/// <summary>PID: 201 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int sysname_201 = 201;
		/// <summary>PID: 201 | Type: write</summary>
		public const int sysname = 201;
		/// <summary>PID: 202 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int syscontact_202 = 202;
		/// <summary>PID: 202 | Type: write</summary>
		public const int syscontact = 202;
		/// <summary>PID: 203 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int syslocation_203 = 203;
		/// <summary>PID: 203 | Type: write</summary>
		public const int syslocation = 203;
		/// <summary>PID: 996 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int streamsratecalculationsmethod_996 = 996;
		/// <summary>PID: 996 | Type: write</summary>
		public const int streamsratecalculationsmethod = 996;
	}
	public class Streams
	{
		/// <summary>PID: 1000</summary>
		public const int tablePid = 1000;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 1001</summary>
		public const int indexColumnPid = 1001;
		public class Pid
		{
			/// <summary>PID: 1001 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int streamsindex_1001 = 1001;
			/// <summary>PID: 1001 | Type: read</summary>
			public const int streamsindex = 1001;
			/// <summary>PID: 1002 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int streamsdrescription_1002 = 1002;
			/// <summary>PID: 1002 | Type: read</summary>
			public const int streamsdrescription = 1002;
			/// <summary>PID: 1003 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int streamsoctetscounter_1003 = 1003;
			/// <summary>PID: 1003 | Type: read</summary>
			public const int streamsoctetscounter = 1003;
			/// <summary>PID: 1004 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int streamsbitrate_1004 = 1004;
			/// <summary>PID: 1004 | Type: read</summary>
			public const int streamsbitrate = 1004;
			/// <summary>PID: 1005 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int streamsbitratedata_1005 = 1005;
			/// <summary>PID: 1005 | Type: read</summary>
			public const int streamsbitratedata = 1005;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int streamsindex_1001 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int streamsindex = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int streamsdrescription_1002 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int streamsdrescription = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int streamsoctetscounter_1003 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int streamsoctetscounter = 2;
			/// <summary>IDX: 3 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int streamsbitrate_1004 = 3;
			/// <summary>IDX: 3 | Type: read</summary>
			public const int streamsbitrate = 3;
			/// <summary>IDX: 4 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int streamsbitratedata_1005 = 4;
			/// <summary>IDX: 4 | Type: read</summary>
			public const int streamsbitratedata = 4;
		}
	}
}
public class WriteParameters
{
	/// <summary>PID: 201  | Type: write</summary>
	public System.Object Sysname {get { return Protocol.GetParameter(201); }set { Protocol.SetParameter(201, value); }}
	/// <summary>PID: 202  | Type: write</summary>
	public System.Object Syscontact {get { return Protocol.GetParameter(202); }set { Protocol.SetParameter(202, value); }}
	/// <summary>PID: 203  | Type: write</summary>
	public System.Object Syslocation {get { return Protocol.GetParameter(203); }set { Protocol.SetParameter(203, value); }}
	/// <summary>PID: 996  | Type: write | DISCREETS: Fast = 1, Accurate = 2</summary>
	public System.Object Streamsratecalculationsmethod {get { return Protocol.GetParameter(996); }set { Protocol.SetParameter(996, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	/// <summary>PID: 1000</summary>
	StreamsQActionTable streams { get; set; }
	object Afterstartup_dummy { get; set; }
	object Readme_9 { get; set; }
	object Readme { get; set; }
	object Fixed_0__fixed { get; set; }
	object Fixed_1__fixed { get; set; }
	object Sysuptimetimeouttrigger_dummy { get; set; }
	object Sysuptimegroupresultafterretries_92 { get; set; }
	object Sysuptimegroupresultafterretries { get; set; }
	object Sysuptimeaftergrouptrigger_dummy { get; set; }
	object Sysuptimebuffer_95 { get; set; }
	object Sysuptimebuffer { get; set; }
	object Sysuptime_100 { get; set; }
	object Sysuptime { get; set; }
	object Sysname_101 { get; set; }
	object Sysname { get; set; }
	object Syscontact_102 { get; set; }
	object Syscontact { get; set; }
	object Syslocation_103 { get; set; }
	object Syslocation { get; set; }
	object Sysdescr_104 { get; set; }
	object Sysdescr { get; set; }
	object Sysname_201 { get; set; }
	object Syscontact_202 { get; set; }
	object Syslocation_203 { get; set; }
	object Countertimeouttrigger_dummy { get; set; }
	object Countergroupafterretries_492 { get; set; }
	object Countergroupafterretries { get; set; }
	object Counteraftergrouptrigger_dummy { get; set; }
	object Countersnmpagentrestartflag_494 { get; set; }
	object Countersnmpagentrestartflag { get; set; }
	object Counter_500 { get; set; }
	object Counter { get; set; }
	object Counterrate_501 { get; set; }
	object Counterrate { get; set; }
	object Counterratedata_502 { get; set; }
	object Counterratedata { get; set; }
	object Streamstimeouttrigger_dummy { get; set; }
	object Streamsgroupafterretries_992 { get; set; }
	object Streamsgroupafterretries { get; set; }
	object Streamsaftergrouptrigger_dummy { get; set; }
	object Streamssnmpagentrestartflag_994 { get; set; }
	object Streamssnmpagentrestartflag { get; set; }
	object Streamsratecalculationsmethod_995 { get; set; }
	object Streamsratecalculationsmethod { get; set; }
	object Streamsratecalculationsmethod_996 { get; set; }
	object Streamsindex_1001 { get; set; }
	object Streamsindex { get; set; }
	object Streamsdrescription_1002 { get; set; }
	object Streamsdrescription { get; set; }
	object Streamsoctetscounter_1003 { get; set; }
	object Streamsoctetscounter { get; set; }
	object Streamsbitrate_1004 { get; set; }
	object Streamsbitrate { get; set; }
	object Streamsbitratedata_1005 { get; set; }
	object Streamsbitratedata { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 1000</summary>
	public StreamsQActionTable streams { get; set; }
	/// <summary>PID: 2  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 9  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Readme_9 {get { return GetParameter(9); }set { SetParameter(9, value); }}
	/// <summary>PID: 9  | Type: read</summary>
	public System.Object Readme {get { return GetParameter(9); }set { SetParameter(9, value); }}
	/// <summary>PID: 10  | Type: fixed</summary>
	public System.Object Fixed_0__fixed {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 11  | Type: fixed</summary>
	public System.Object Fixed_1__fixed {get { return GetParameter(11); }set { SetParameter(11, value); }}
	/// <summary>PID: 91  | Type: dummy</summary>
	public System.Object Sysuptimetimeouttrigger_dummy {get { return GetParameter(91); }set { SetParameter(91, value); }}
	/// <summary>PID: 92  | Type: read | DISCREETS: Success = 0, Timeout = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Sysuptimegroupresultafterretries_92 {get { return GetParameter(92); }set { SetParameter(92, value); }}
	/// <summary>PID: 92  | Type: read | DISCREETS: Success = 0, Timeout = 1</summary>
	public System.Object Sysuptimegroupresultafterretries {get { return GetParameter(92); }set { SetParameter(92, value); }}
	/// <summary>PID: 93  | Type: dummy</summary>
	public System.Object Sysuptimeaftergrouptrigger_dummy {get { return GetParameter(93); }set { SetParameter(93, value); }}
	/// <summary>PID: 95  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Sysuptimebuffer_95 {get { return GetParameter(95); }set { SetParameter(95, value); }}
	/// <summary>PID: 95  | Type: read</summary>
	public System.Object Sysuptimebuffer {get { return GetParameter(95); }set { SetParameter(95, value); }}
	/// <summary>PID: 100  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Sysuptime_100 {get { return GetParameter(100); }set { SetParameter(100, value); }}
	/// <summary>PID: 100  | Type: read</summary>
	public System.Object Sysuptime {get { return GetParameter(100); }set { SetParameter(100, value); }}
	/// <summary>PID: 101  | Type: read | EXCEPTIONS: N/A = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Sysname_101 {get { return GetParameter(101); }set { SetParameter(101, value); }}
	/// <summary>PID: 101  | Type: read | EXCEPTIONS: N/A = -1</summary>
	public System.Object Sysname {get { return GetParameter(101); }set { SetParameter(101, value); }}
	/// <summary>PID: 102  | Type: read | EXCEPTIONS: N/A = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Syscontact_102 {get { return GetParameter(102); }set { SetParameter(102, value); }}
	/// <summary>PID: 102  | Type: read | EXCEPTIONS: N/A = -1</summary>
	public System.Object Syscontact {get { return GetParameter(102); }set { SetParameter(102, value); }}
	/// <summary>PID: 103  | Type: read | EXCEPTIONS: N/A = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Syslocation_103 {get { return GetParameter(103); }set { SetParameter(103, value); }}
	/// <summary>PID: 103  | Type: read | EXCEPTIONS: N/A = -1</summary>
	public System.Object Syslocation {get { return GetParameter(103); }set { SetParameter(103, value); }}
	/// <summary>PID: 104  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Sysdescr_104 {get { return GetParameter(104); }set { SetParameter(104, value); }}
	/// <summary>PID: 104  | Type: read</summary>
	public System.Object Sysdescr {get { return GetParameter(104); }set { SetParameter(104, value); }}
	/// <summary>PID: 201  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Sysname_201 {get { return GetParameter(201); }set { SetParameter(201, value); }}
	/// <summary>PID: 202  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Syscontact_202 {get { return GetParameter(202); }set { SetParameter(202, value); }}
	/// <summary>PID: 203  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Syslocation_203 {get { return GetParameter(203); }set { SetParameter(203, value); }}
	/// <summary>PID: 491  | Type: dummy</summary>
	public System.Object Countertimeouttrigger_dummy {get { return GetParameter(491); }set { SetParameter(491, value); }}
	/// <summary>PID: 492  | Type: read | DISCREETS: Success = 0, Timeout = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Countergroupafterretries_492 {get { return GetParameter(492); }set { SetParameter(492, value); }}
	/// <summary>PID: 492  | Type: read | DISCREETS: Success = 0, Timeout = 1</summary>
	public System.Object Countergroupafterretries {get { return GetParameter(492); }set { SetParameter(492, value); }}
	/// <summary>PID: 493  | Type: dummy</summary>
	public System.Object Counteraftergrouptrigger_dummy {get { return GetParameter(493); }set { SetParameter(493, value); }}
	/// <summary>PID: 494  | Type: read | DISCREETS: Not Restarted = 0, Restarted = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Countersnmpagentrestartflag_494 {get { return GetParameter(494); }set { SetParameter(494, value); }}
	/// <summary>PID: 494  | Type: read | DISCREETS: Not Restarted = 0, Restarted = 1</summary>
	public System.Object Countersnmpagentrestartflag {get { return GetParameter(494); }set { SetParameter(494, value); }}
	/// <summary>PID: 500  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Counter_500 {get { return GetParameter(500); }set { SetParameter(500, value); }}
	/// <summary>PID: 500  | Type: read</summary>
	public System.Object Counter {get { return GetParameter(500); }set { SetParameter(500, value); }}
	/// <summary>PID: 501  | Type: read | EXCEPTIONS: N/A = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Counterrate_501 {get { return GetParameter(501); }set { SetParameter(501, value); }}
	/// <summary>PID: 501  | Type: read | EXCEPTIONS: N/A = -1</summary>
	public System.Object Counterrate {get { return GetParameter(501); }set { SetParameter(501, value); }}
	/// <summary>PID: 502  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Counterratedata_502 {get { return GetParameter(502); }set { SetParameter(502, value); }}
	/// <summary>PID: 502  | Type: read</summary>
	public System.Object Counterratedata {get { return GetParameter(502); }set { SetParameter(502, value); }}
	/// <summary>PID: 991  | Type: dummy</summary>
	public System.Object Streamstimeouttrigger_dummy {get { return GetParameter(991); }set { SetParameter(991, value); }}
	/// <summary>PID: 992  | Type: read | DISCREETS: Success = 0, Timeout = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streamsgroupafterretries_992 {get { return GetParameter(992); }set { SetParameter(992, value); }}
	/// <summary>PID: 992  | Type: read | DISCREETS: Success = 0, Timeout = 1</summary>
	public System.Object Streamsgroupafterretries {get { return GetParameter(992); }set { SetParameter(992, value); }}
	/// <summary>PID: 993  | Type: dummy</summary>
	public System.Object Streamsaftergrouptrigger_dummy {get { return GetParameter(993); }set { SetParameter(993, value); }}
	/// <summary>PID: 994  | Type: read | DISCREETS: Not Restarted = 0, Restarted = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streamssnmpagentrestartflag_994 {get { return GetParameter(994); }set { SetParameter(994, value); }}
	/// <summary>PID: 994  | Type: read | DISCREETS: Not Restarted = 0, Restarted = 1</summary>
	public System.Object Streamssnmpagentrestartflag {get { return GetParameter(994); }set { SetParameter(994, value); }}
	/// <summary>PID: 995  | Type: read | DISCREETS: Fast = 1, Accurate = 2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streamsratecalculationsmethod_995 {get { return GetParameter(995); }set { SetParameter(995, value); }}
	/// <summary>PID: 995  | Type: read | DISCREETS: Fast = 1, Accurate = 2</summary>
	public System.Object Streamsratecalculationsmethod {get { return GetParameter(995); }set { SetParameter(995, value); }}
	/// <summary>PID: 996  | Type: write | DISCREETS: Fast = 1, Accurate = 2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streamsratecalculationsmethod_996 {get { return GetParameter(996); }set { SetParameter(996, value); }}
	/// <summary>PID: 1001  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streamsindex_1001 {get { return GetParameter(1001); }set { SetParameter(1001, value); }}
	/// <summary>PID: 1001  | Type: read</summary>
	public System.Object Streamsindex {get { return GetParameter(1001); }set { SetParameter(1001, value); }}
	/// <summary>PID: 1002  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streamsdrescription_1002 {get { return GetParameter(1002); }set { SetParameter(1002, value); }}
	/// <summary>PID: 1002  | Type: read</summary>
	public System.Object Streamsdrescription {get { return GetParameter(1002); }set { SetParameter(1002, value); }}
	/// <summary>PID: 1003  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streamsoctetscounter_1003 {get { return GetParameter(1003); }set { SetParameter(1003, value); }}
	/// <summary>PID: 1003  | Type: read</summary>
	public System.Object Streamsoctetscounter {get { return GetParameter(1003); }set { SetParameter(1003, value); }}
	/// <summary>PID: 1004  | Type: read | EXCEPTIONS: N/A = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streamsbitrate_1004 {get { return GetParameter(1004); }set { SetParameter(1004, value); }}
	/// <summary>PID: 1004  | Type: read | EXCEPTIONS: N/A = -1</summary>
	public System.Object Streamsbitrate {get { return GetParameter(1004); }set { SetParameter(1004, value); }}
	/// <summary>PID: 1005  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streamsbitratedata_1005 {get { return GetParameter(1005); }set { SetParameter(1005, value); }}
	/// <summary>PID: 1005  | Type: read</summary>
	public System.Object Streamsbitratedata {get { return GetParameter(1005); }set { SetParameter(1005, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		streams = new StreamsQActionTable(this, 1000, "streams");
		Write = new WriteParameters(this);
	}
}
/// <summary>IDX: 0</summary>
public class StreamsQActionTable : QActionTable, IEnumerable<StreamsQActionRow>
{
	public StreamsQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<StreamsQActionRow> GetEnumerator() { return new QActionTableEnumerator<StreamsQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class StreamsQActionRow : QActionTableRow
{
	/// <summary>PID: 1001 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streamsindex_1001 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1001 | Type: read</summary>
	public System.Object Streamsindex { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1002 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streamsdrescription_1002 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1002 | Type: read</summary>
	public System.Object Streamsdrescription { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1003 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streamsoctetscounter_1003 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 1003 | Type: read</summary>
	public System.Object Streamsoctetscounter { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 1004 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streamsbitrate_1004 { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 1004 | Type: read</summary>
	public System.Object Streamsbitrate { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 1005 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streamsbitratedata_1005 { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 1005 | Type: read</summary>
	public System.Object Streamsbitratedata { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	public StreamsQActionRow() : base(0, 5) { }
	public StreamsQActionRow(System.Object[] oRow) : base(0, 5, oRow) { }
	public static implicit operator StreamsQActionRow(System.Object[] source) { return new StreamsQActionRow(source); }
	public static implicit operator System.Object[](StreamsQActionRow source) { return source.ToObjectArray(); }
}
}
